name: Enflame-Build-And-Test

on:
  push:
    branches: [ "triton_v3.3.x" ]
  pull_request:
    branches: [ "triton_v3.3.x" ]

jobs:
  enflame-build-and-test:
    uses: flagos-ai/flagtree/.github/workflows/enflame-build-and-test.yml@workflow_unifiy