name: Metax-Build-And-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  metax-build-and-test:
    runs-on: metax
    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: FlagTree Build on Metax
        shell: bash
        run: |
          set -x
          pip uninstall -y triton
          source ~/env.sh
          export FLAGTREE_BACKEND=metax
          cd python
          MAX_JOBS=32 python3.10 -m pip install . --no-build-isolation

      - name: FlagTree Test on Metax
        shell: bash
        run: |
          set -x
          python3.10 -m pytest -s third_party/metax/python/test/unit
